---
- name: Download Git Credential Manager tarball
  get_url:
    url: https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.0.935/gcm-linux_amd64.2.0.935.tar.gz
    dest: /tmp/gcm-linux_amd64.2.0.935.tar.gz
  register: gcm_download_archive

- name: Unarchive and install Git Credential Manager
  become: true
  unarchive: 
    src: /tmp/gcm-linux_amd64.2.0.935.tar.gz
    dest: /usr/local/bin
  when: gcm_download_archive