- name: Import Google signing key
  become: true
  ansible.builtin.rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add Google Chrome repository into repo.d list
  become: true
  ansible.builtin.yum_repository:
    name: google-chrome
    description: google-chrome repository
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub

- name: Install google-chrome-stable
  become: true
  ansible.builtin.yum:
    name: "google-chrome-stable"
    state: latest
    update_cache: true
