---
- name: Install distribution-gpg-keys
  become: true
  ansible.builtin.dnf:
    name: distribution-gpg-keys
    state: present

- name: Install fedora-workstation-repositories
  become: true
  ansible.builtin.dnf:
    name: fedora-workstation-repositories
    state: present

- name: Install System Packages
  become: true
  ansible.builtin.dnf:
    name: "{{ fedora_packages__packages }}"
    state: latest
    update_cache: true

- name: Install Google Chrome
  ansible.builtin.import_tasks: google-chrome.yml

- name: Install VS Code
  ansible.builtin.import_tasks: vs-code.yml

- name: Install Git Credential Manager
  ansible.builtin.import_tasks: git-credential-manager.yml

- name: Install Terraform
  ansible.builtin.import_tasks: terraform.yml

- name: Install Kubectl
  ansible.builtin.import_tasks: kubectl.yml

- name: Install Flatpaks
  community.general.flatpak:
    name: "{{ fedora_packages__flatpaks }}"
    state: present