---
- name: Setup workstation
  hosts: all
  vars_files:
    - "vars.yml"
  roles:
    - {role: 'fedora_packages', tags: 'packages' }
    - role: gantsign.oh-my-zsh
      tags: oh-my-zsh
      plugins:
        - docker
        - docker-compose
        - kube-ps1
        - git
        - github
        - zsh-autosuggestions
        - zsh-syntax-highlighting
      users:
        - username: "{{ ansible_user_id }}"
        - username: root
    - { role: 'dotfiles', tags: 'dotfiles' }
    - { role: 'system', tags: 'system' }
    - role: petermosmans.customize-gnome
      tags: gnome
      gnome_extensions:
        - id: 1460
          enable: true
