---
- name: Setup workstation
  hosts: all
  vars_files:
    - "vars.yml"
  roles:
    - {role: 'fedora_packages', tags: 'packages' }
    - role: gantsign.oh-my-zsh
      tags: oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
          oh_my_zsh:
            plugins:
            - docker
            - docker-compose
            - kube-ps1
            - git
            - github
            - zsh-autosuggestions
            - zsh-syntax-highlighting
        - username: root
    - { role: 'dotfiles', tags: 'dotfiles' }
    - { role: 'system', tags: 'system' }
    - role: petermosmans.customize-gnome
      tags: gnome
      gnome_extensions:
        - { id: 1460, enable: true } # https://extensions.gnome.org/extension/1460/vitals/
        - { id: 302, enable: true } # https://extensions.gnome.org/extension/302/windowoverlay-icons/
        - { id: 1162, enable: true } # https://extensions.gnome.org/extension/1162/emoji-selector/
        - { id: 8, enable: true } # https://extensions.gnome.org/extension/8/places-status-indicator/
        - { id: 6, enable: false } # https://extensions.gnome.org/extension/6/applications-menu/
        - { id: 3628, enable: true} # https://extensions.gnome.org/extension/3628/arcmenu/
        - { id: 1319, enable: true } # https://extensions.gnome.org/extension/1319/gsconnect/
        - { id: 744, enable: false } # https://extensions.gnome.org/extension/744/hide-activities-button/
        - { id: 5311, enable: true } # https://extensions.gnome.org/extension/5311/activities-workspace-name/
        - { id: 5410, enable: true } # https://extensions.gnome.org/extension/5410/grand-theft-focus/
        - { id: 4642, enable: true } # https://extensions.gnome.org/extension/4642/mouse-follows-focus/
        - { id: 1485, enable: true } # https://extensions.gnome.org/extension/1485/workspace-matrix/
        - { id: 3994, enable: true } # https://extensions.gnome.org/extension/3994/all-ip-addresses/
        - { id: 307, enable: false } # https://extensions.gnome.org/extension/307/dash-to-dock/
        - { id: 1160, enable: true } # https://extensions.gnome.org/extension/1160/dash-to-panel/
        - { id: 779, enable: true } # https://extensions.gnome.org/extension/779/clipboard-indicator/
        - { id: 97, enable: true } # https://extensions.gnome.org/extension/97/coverflow-alt-tab/