---
- name: Install zsh-autosuggestions repo
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting repo
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Link zshrc.custom
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/rcfiles/zshrc.custom"
    dest: "{{ ansible_user_dir }}/.zshrc.custom"
    state: link

- name: Source .zshrc.custom in .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    regexp: '^source {{ ansible_user_dir }}/.zshrc.custom$'
    line: 'source {{ ansible_user_dir }}/.zshrc.custom'
    state: present
