---

- name: Setup Work Folders
  ansible.builtin.import_tasks: setup_workfolders.yml

- name: Setup Git
  ansible.builtin.import_tasks: setup_git.yml

- name: Configure ZSH
  ansible.builtin.import_tasks: configure_zsh.yml
